[theme]
base = "light"
primaryColor = "#2a9d8f"  # Teal/green for buttons & highlights
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7f8"
textColor = "#264653"     # Deep slate for good readability
font = "sans serif"
