[theme]
base = "light"
primaryColor = "#0077b6"   # Blue button background
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9f9f9"
textColor = "#ffffff"      # Button text is white
font = "sans serif"
